version: '3'
services:
  redis7000:
    image: redis-cluster
    restart: always
    hostname: redis7000
    container_name: redis7000
    ports:
      - 7000:7000
      - 17000:17000
    volumes:
      - ./redis7000.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
  redis7001:
    image: redis-cluster
    restart: always
    hostname: redis7001
    container_name: redis7001
    ports:
      - 7001:7001
      - 17001:17001
    volumes:
      - ./redis7001.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
  redis8000:
    image: redis-cluster
    restart: always
    hostname: redis8000
    container_name: redis8000
    ports:
      - 8000:8000
      - 18000:18000
    volumes:
      - ./redis8000.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
  redis8001:
    image: redis-cluster
    restart: always
    hostname: redis8001
    container_name: redis8001
    ports:
      - 8001:8001
      - 18001:18001
    volumes:
      - ./redis8001.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
  redis9000:
    image: redis-cluster
    restart: always
    hostname: redis9000
    container_name: redis9000
    ports:
      - 9000:9000
      - 19000:19000
    volumes:
      - ./redis9000.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
  redis9001:
    image: redis-cluster
    restart: always
    hostname: redis9001
    container_name: redis9001
    ports:
      - 9001:9001
      - 19001:19001
    volumes:
      - ./redis9001.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M