version: '3'
services:
  redis7000:
    image: redis-cluster
    restart: always
    hostname: redis7000
    container_name: redis7000
    networks:
      omc:
        ipv4_address: 172.16.0.100
    ports:
      - 7000:6379
      - 17000:16379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
  redis7001:
    image: redis-cluster
    restart: always
    hostname: redis7001
    container_name: redis7001
    networks:
      omc:
        ipv4_address: 172.16.0.101
    ports:
      - 7001:6379
      - 17001:16379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
  redis8000:
    image: redis-cluster
    restart: always
    hostname: redis8000
    container_name: redis8000
    networks:
      omc:
        ipv4_address: 172.16.0.102
    ports:
      - 8000:6379
      - 18000:16379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
  redis8001:
    image: redis-cluster
    restart: always
    hostname: redis8001
    container_name: redis8001
    networks:
      omc:
        ipv4_address: 172.16.0.103
    ports:
      - 8001:6379
      - 18001:16379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
  redis9000:
    image: redis-cluster
    restart: always
    hostname: redis9000
    container_name: redis9000
    networks:
      omc:
        ipv4_address: 172.16.0.104
    ports:
      - 9000:6379
      - 19000:16379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
  redis9001:
    image: redis-cluster
    restart: always
    hostname: redis9001
    container_name: redis9001
    networks:
      omc:
        ipv4_address: 172.16.0.105
    ports:
      - 9001:6379
      - 19001:16379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 256M
networks:
  omc:
    external: true