spring:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mysql:3306/ody?serverTimezone=Asia/Shanghai
      username: ody
      password: bB%jZmT7URVqsJ
    jira:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.10.0.7:3306/jiradb?serverTimezone=Asia/Shanghai
      username: loveandpeace
      password: E0xy3Z7W
  jackson:
    time-zone: GMT+8
    date-format: 'yyyy-MM-dd HH:mm:ss'
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    mongodb:
      port: 27017
      database: nginx
      host: mongod
  redis:
    port: 6379
    host: redis
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  profiles:
    active:
server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
xxl:
  addresses: http://xxl:8080/xxl-job-admin
  appname: utils
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
tencent:
  token: CoqEjSL1pBG4bDA7mKNcJY2dyHnIgwV8
util:
  git-dir: /data/sql
  run-sql-sh: /data/runSql.sh
logging:
  level:
    root: info
  path: /data/log/
rp:
  root-file-path: /data/rp