version: '3'
services:
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    networks:
      - mbiscuit
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    command: nginx
    deploy:
      resources:
        limits:
          memory: 128M
networks:
  mbiscuit:
    external: true