version: '3'
services:
  static:
    image: static
    restart: always
    hostname: static
    container_name: static
    networks:
      - mbiscuit
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /data/static:/data
    command: nginx
    deploy:
      resources:
        limits:
          memory: 128M
networks:
  mbiscuit:
    external: true