version: '3'
services:
  mysql:
    image: mysql8
    restart: always
    hostname: mysql
    container_name: mysql
    networks:
      - mbiscuit
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=nCWC[ja2wiecRi"
    deploy:
      resources:
        limits:
          memory: 1024M
networks:
  mbiscuit:
    external: true