version: '3'
services:
  rp:
    image: rp
    restart: always
    hostname: rp
    container_name: rp
    networks:
      - mbiscuit
    ports:
      - 2294:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/rp:/data
    command: nginx
    deploy:
      resources:
        limits:
          memory: 128M
networks:
  mbiscuit:
    external: true