version: '3'
services:
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    networks:
      - mbiscuit
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 512M
networks:
  mbiscuit:
    external: true